### ISSUE TITLE
HTML Editor task list

### ISSUE THREAD

**Issue by tesseralis** [components-ai/css.gui#214]
Things to do for our HTML editor:

* [ ] be able to add and remove HTML tags
* [ ] be able to edit HTML attributes
* [ ] be able to edit and add string inputs

**Comment by johno** [comment]
For moving HTML content around, particularly in the tree view, might be worth us checking out: https://github.com/minop1205/react-dnd-treeview
